spring:
  application:
    name: employee-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring
    username: spring
    password: spring123

server.port: 8090

management:
  endpoints.web.exposure.include: '*'
  endpoint.health:
    show-details: always
    probes:
      enabled: true